global:
  scrape_interval:     15s
  evaluation_interval: 15s

#rule_files:
  # - "first.rules"
  # - "second.rules"
#告警组件
alerting:
  alertmanagers:
  - static_configs:
    - targets:
        - alertmanager:9093

 #告警策略文件
rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091']
        labels:
          instance: pushgateway
  - job_name: 'consul'
    consul_sd_configs:
      - server: 'consul:8500'
        services: []
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job

      # 添加一个location标签方便定位机房
      - source_labels: [__meta_consul_node]
        regex: "(.*)"
        replacement: $1
        action: replace
        target_label: "location"
