version: '2'

networks:
  xl_app:

services:
  mysql:
    container_name: mysql
    image: mysql:5.7.29
    networks:
      - xl_app
    ports:
      - 3306:3306
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root001
      - LANG=C.UTF-8
    restart: always
    volumes:
      - /tmp/mysql:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    command: " --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-allowed-packet=20971520"

